background bg.png
text 5 1.1. Create a cube
video 0:10 install_blender.mp4
text 5 1.1.1. Install Blender
video 10:20 install_blender.mp4
text 5 1.1.2. Create a deformed cube

text 5 1.1.3. Triangulate the cube: CRITICAL for mobile/web

text 5 1.1.4. UV unwrap the cube for later texturing

text 5 1.1.5. Save the model

text 5 1.1.6. Install Blender-to-OpenSceneGraph exporter

text 5 1.1.7. Export Blender model to OpenSceneGraph format

text 5 1.1. That's it for creating a cube

