#!/usr/bin/python2

import os, sys
from Parser import *

if (len(sys.argv) != 2):
    print "Usage: {0} /path/to/tutorial.script".format(sys.argv[0])
    sys.exit(0)

fileIn = sys.argv[1]
#binDir = os.path.dirname(sys.argv[0])
#fileName = os.path.splitext(os.path.basename(fileIn))[0]
dstDir = os.path.dirname(fileIn)

parser = Parser()
with (open(fileIn, "r")) as f:
    linesIn = f.readlines()
    parser.parseLines(linesIn)

parser.printTree()
