#!/usr/bin/python

import os
import sys
import tempfile
from Common import *
from ImgBaker import *
from MLTBaker import *
from Parser import *

if (len(sys.argv) != 2):
    print("Usage: {0} /path/to/tutorial.script".format(sys.argv[0]))
    sys.exit(0)

fileIn = sys.argv[1]
#binDir = os.path.dirname(sys.argv[0])
#fileName = os.path.splitext(os.path.basename(fileIn))[0]
fileInDir = os.path.dirname(fileIn) + "/"
dstDir = tempfile.gettempdir() + "/tutorial-tool-cache/"

# Create dst dir.
if (not os.path.exists(dstDir)):
    os.mkdir(dstDir)

parser = Parser()
with (open(fileIn, "r")) as f:
    linesIn = f.readlines()
    parser.parseLines(linesIn)

#parser.printTree()

imgBaker = ImgBaker()
imgBaker.bake(parser.background, parser.items, dstDir, fileInDir)

mltBaker = MLTBaker(dstDir, MIX_LEN)
mltBaker.bake(parser.items, fileInDir)

print("# BASH script begins")
print(imgBaker.script())
print(mltBaker.script())
print("# BASH script ends")

