#!/usr/bin/python

import sys
from Common import *
from YoutubeTimestampBaker import *
from Parser import *

if (len(sys.argv) != 2):
    print("Usage: {0} /path/to/tutorial.script".format(sys.argv[0]))
    sys.exit(0)

fileIn = sys.argv[1]

parser = Parser()
with (open(fileIn, "r")) as f:
    linesIn = f.readlines()
    parser.parseLines(linesIn)

ytBaker = YoutubeTimestampBaker(MIX_LEN)
ytBaker.bake(parser.items)

print("# YouTube timestamps begin")
print(ytBaker.script())
print("# YouTube timestamps end")

